# Generated by Django 4.0.4 on 2022-06-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='img',
            field=models.ImageField(blank=True, default='default.png', upload_to='images'),
        ),
    ]
