# Generated by Django 4.0.4 on 2022-06-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='img',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
